src/objects/CommonApp_DataMapping__c.object
<CustomObject>
    <label>CommonApp DataMapping</label>
    <nameField>
        <label>CommonApp DataMapping Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CommonApp DataMappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Final_Field__c</fullName>
        <inlineHelpText>The final field destination this Common App field should be mapped to</inlineHelpText>
        <label>Final Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Final_Object__c</fullName>
        <inlineHelpText>Select the object which this CA field should be stored in</inlineHelpText>
        <label>Final Object</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Contact</fullName>
                </value>
                <value>
                    <fullName>Application__c</fullName>
                </value>
                <value>
                    <fullName>Address__c</fullName>
                </value>
                <value>
                    <fullName>Education_History__c</fullName>
                </value>
                <value>
                    <fullName>Contact_Language__c</fullName>
                </value>
                <value>
                    <fullName>Relationship__c</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Mapped_to__c</fullName>
        <inlineHelpText>Select the type of field this Common App field should be mapped to</inlineHelpText>
        <label>Mapped to</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>JSON</fullName>
                </value>
                <value>
                    <fullName>Field</fullName>
                </value>
                <value>
                    <fullName>Both</fullName>
                </value>
                <value>
                    <fullName>Either</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Structure__c</fullName>
        <inlineHelpText>Structure name for this Common App field</inlineHelpText>
        <label>Structure</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/CommonApp_Integration_Setup__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>CommonApp Integration Setup</label>
    <fields>
        <fullName>Common_App_ID__c</fullName>
        <inlineHelpText>Map Common App ID to this custom field.</inlineHelpText>
        <label>Common App ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/DataMapper2.cls
public class DataMapper2 {

	public static void testRun() {
        List<Map<String,Object>> jsonObjKey = JSONBuilder.runBuilder('CommonApp', 'Student'); 
        
        main(jsonObjKey); 
    }

    public static void main(List<Map<String,Object>> commonAppValuesByField) {
    	
    	Map<String, CommonApp_DataMapping__c> dataMappingByJSONStructure = retrieveDataMappingObj(); 

    	String commonAppIdField = checkCommonAppCustomSetting(); 

    	Map<String,List<CASFDCMapping>> masterDataMapping = constructMasterMap(commonAppValuesByField, dataMappingByJSONStructure); 
        
        checkObjToCreate (masterDataMapping); 
    }

    public static Map<String, CommonApp_DataMapping__c> retrieveDataMappingObj() {
        Map<String, CommonApp_DataMapping__c> dataMappingByJSONStructure = new Map<String, CommonApp_DataMapping__c>(); 
        
        List<CommonApp_DataMapping__c> dataMappingList = [SELECT Id, Name, Structure__c, 
        													Final_Object__c, Final_Field__c, Mapped_to__c 
                                                          	FROM CommonApp_DataMapping__c]; 

        for (CommonApp_DataMapping__c cd : dataMappingList) {
            dataMappingByJSONStructure.put(cd.Structure__c, cd); 
        }

        return dataMappingByJSONStructure; 
        
    }

    public static String checkCommonAppCustomSetting() {
        String commonAppIdField = ''; 

        CommonApp_Integration_Setup__c caIDMapping = CommonApp_Integration_Setup__c.getOrgDefaults(); 
        
        Set<String> conFields = Schema.SObjectType.Contact.fields.getMap().keySet();

        for (String conField : conFields) {
            if (conField == caIDMapping.Common_App_ID__c) {
                commonAppIdField = conField;
            }
        }

        return commonAppIdField; 
    }

    public static Map<String,List<CASFDCMapping>> constructMasterMap(List<Map<String,Object>> commonAppValuesByField, Map<String, CommonApp_DataMapping__c> dataMappingByJSONStructure) {
        Map<String,List<CASFDCMapping>> mappingsByObj = new Map<String,List<CASFDCMapping>>(); 
        
        for (CommonApp_DataMapping__c dm : dataMappingByJSONStructure.values()) {
       		CASFDCMapping caMap = new CASFDCMapping();
            caMap.structure = dm.Structure__c; 
            caMap.fieldName = dm.Final_Field__c; 
            caMap.objectName = dm.Final_Object__c; 
								
            String objectName = dm.Final_Object__c; 
            List<CASFDCMapping> existingMaps = new List<CASFDCMapping>(); 
            if (mappingsByObj.containsKey(objectName)) {
            	existingMaps = mappingsByObj.get(objectName); 
           	} 
            existingMaps.add(caMap); 
			mappingsByObj.put(dm.Final_Object__c, existingMaps);                             
            System.debug('mappingsByObj -->' + mappingsByObj);      
        }
        
        /*if (!commonAppValuesByField.isEmpty()) {
    		for (Map<String, Object> checkStud : commonAppValuesByField) {
                System.debug('checkStud -->' + checkStud); 
    			
                for (String key : checkStud.keySet()) {
                    System.debug('key -->' + key); 
    				
                    if (dataMappingByJSONStructure.containsKey(key)) {
                        System.debug('keyIsFound on DM -->'); 
                        for (Object caVal : checkStud.values()) {
                            System.debug('caVal -->' + caVal);
                            System.debug('keyCheck2 -->' + key); 
                                CASFDCMapping caMap = new CASFDCMapping();
                                caMap.structure = key; 
                                caMap.fieldName = dataMappingByJSONStructure.get(key).Final_Field__c; 
                                caMap.objectName  = dataMappingByJSONStructure.get(key).Final_Object__c; 
								
                            	String objectName  = dataMappingByJSONStructure.get(key).Final_Object__c; 
                            	List<CASFDCMapping> existingMaps = new List<CASFDCMapping>(); 
                                if (mappingsByObj.containsKey(objectName)) {
                                    existingMaps = mappingsByObj.get(objectName); 
                                } 
                                existingMaps.add(caMap); 
								mappingsByObj.put(dataMappingByJSONStructure.get(key).Final_Object__c, existingMaps);                             
                            
    					} 
                    }    
    			}
    		}
    	}*/ 
        System.debug('mappingsByObj -->' + mappingsByObj.get('Contact')); 
    	return mappingsByObj; 
    }
    
    public static void checkObjToCreate(Map<String,List<CASFDCMapping>> masterMappingMap) {
        Map<String,Map<String,Object>> contactValuesForContact = new Map<String,Map<String,Object>>(); 
        //Group by Object to create
        for (String caKey : masterMappingMap.keySet()) {
            /*for (CASFDCMapping valObj : masterMappingMap.values()) {
                for (String jsonStr : valObj.structures) {
                    if (jsonStr == caKey) {
                        //contactValuesForContact.put(masterMappingMap.get(caKey));
                    }
                }
            }*/ 
        }
        
    }
}