src/objects/JSONBuilderSchema__mdt.object
<CustomObject>
    <description>This is used for storing the JSON structure to be used for building the final JSON string for the integrations&lt;</description>
    <label>JSONBuilderSchema</label>
    <pluralLabel>JSONBuilderSchemas</pluralLabel>
    <fields>
        <fullName>Mapped_To__c</fullName>
        <label>Mapped To?</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SFDC_Field_Name__c</fullName>
        <label>SFDC Field Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SourceAttribute__c</fullName>
        <inlineHelpText>This is the attribute in the Proxy Object JSON field that we need to assess</inlineHelpText>
        <label>Source Attribute</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SourceType__c</fullName>
        <inlineHelpText>This is the Proxy Object type we want to assess</inlineHelpText>
        <label>Source Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Structure__c</fullName>
        <inlineHelpText>This will dictate the structure in the destination JSON string.</inlineHelpText>
        <label>Structure</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/ProxyObject__c.object
<CustomObject>
    <label>Proxy Object</label>
    <nameField>
        <label>ProxyObject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProxyObject</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>FinalJSON__c</fullName>
        <label>FinalJSON</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <inlineHelpText>This is the third party system where the data is coming from</inlineHelpText>
        <label>Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/DataMapper.cls
public class DataMapper {
    
    public static void main(ProxyObject__c po) {
   		Map<String, String> schemaMapper = retrieveKeyField(); 
        checkObject(po, schemaMapper); 
        //Check which object and call the method that handles per object creation
    }
    
    //Retrieves the JSONSchemaBuilder CMT 
    public static List<JSONBuilderSchema__mdt> retrieveJSONSchemaBuilder() {
        String sourceType = 'Student';
        String sourceApp = 'CommonApp';
        List<JSONBuilderSchema__mdt> schema = [SELECT SourceType__c, SourceAttribute__c, Structure__c, Order__c,
                                               Object__c, Mapped_To__c, SFDC_Field_Name__c
                                               FROM JSONBuilderSchema__mdt 
                                               WHERE SourceType__c =: sourceType AND
                                                     Source__c =: sourceApp
                                               ORDER BY Order__c ASC
                                               ];
       
        return schema;
    }
    
    //Method that constructs Map<String,String> where SourceAttribute is Key and Value is a string of Object/Field/Mapper
    public static Map<String,String> retrieveKeyField() {
        List<JSONBuilderSchema__mdt> schema = retrieveJSONSchemaBuilder(); 
        Map<String,String> schemaMapper = new Map<String,String>(); 
        for (JSONBuilderSchema__mdt sch : schema) {
            if (String.isNotBlank(sch.SourceAttribute__c) &&
                String.isNotBlank(sch.Object__c) && 
               	String.isNotBlank(sch.Mapped_To__c) && 
               	String.isNotBlank(sch.SFDC_Field_Name__c)) 
            {
                    String valueString = sch.Mapped_To__c + ';' + sch.Object__c + ';' + sch.SFDC_Field_Name__c; 
                   	schemaMapper.put(sch.SourceAttribute__c, valueString); 
            }
        }
        return schemaMapper; 
    }
    
    public static void checkObject(ProxyObject__c po, Map<String,String> schemaMapper) {
        String mapType = ''; 
        
        if (String.isNotBlank(po.FinalJSON__c)) {
            if (schemaMapper.containsKey(po.FinalJSON__c)) {
                mapType = schemaMapper.get(po.FinalJSON__c); 
                //Split the string and remove the 1st value
                //Check if that value = JSON or FIeld 
                
            }
        }
    }
    
}