src/objects/ProxyObject__c.object
<CustomObject>
    <label>Proxy Object</label>
    <nameField>
        <label>ProxyObject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProxyObject</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>FinalJSON__c</fullName>
        <label>FinalJSON</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>JSON__c</fullName>
        <inlineHelpText>This field stores a JSON format data structure which belongs to the proxy object.</inlineHelpText>
        <label>JSON</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Processed__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Denotes whether this has been previously processed.</inlineHelpText>
        <label>Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <inlineHelpText>This is the third party system where the data is coming from</inlineHelpText>
        <label>Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>The entity type this object represents</inlineHelpText>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/SampleBatch.cls
global class SampleBatch implements Database.Batchable<sObject> {
	
    global Database.QueryLocator start(Database.BatchableContext bc) {
       	return Database.getQueryLocator(
            'SELECT Id, FinalJSON__c, JSON__c, Source__c, Type__c FROM ProxyObject__c WHERE Processed__c = False'
        ); 
    }
    
    global void execute(Database.BatchableContext bc, List<ProxyObject__c> records){
        if (records.isEmpty()) {
            return; 
        } 
        
        for (ProxyObject__c po : records) {
            
        }
        
        //Non Bulk 
        /*for (ProxyObject__c po : records) {
            if (String.isNotBlank(po.Type__c) && String.isNotBlank(po.Source__c)) {
                JSONBuilder.saveToProxy(po.Source__c, po.Type__c); 
                //Calls Data Mapper? 
                if (String.isNotBlank(po.FinalJSON__c))  {
                    DataMapper.main(po); 
                }
            } 
        }*/ 
        
        
        //Assuming that this is only for first years 
        /*List<SObject> jsonRecords = new List<SObject>(); 
        for (ContentNote contentNote : records) {
        	jsonRecords.add(contentNote); 
        }
        
        if (!jsonRecords.isEmpty()) {
            ObjectSerializer.main(jsonRecords); 
        }*/ 
       	
    }    
    
    global void finish(Database.BatchableContext bc){
    }    
}